# Generated by Django 5.0.9 on 2026-08-27 01:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acct', '0002_initial'),
        ('gym_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Body Fat (%)')),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Muscle Mass (kg)')),
                ('measurements', models.JSONField(blank=True, default=dict, verbose_name='Measurements')),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Chest (cm)')),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Waist (cm)')),
                ('hips_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Hips (cm)')),
                ('arm_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Arm (cm)')),
                ('thigh_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Thigh (cm)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to='acct.clientprofile', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
            ],
            options={
                'verbose_name': 'Body Measurement',
                'verbose_name_plural': 'Body Measurements',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['client', '-date'], name='body_measur_client__c10cd2_idx')],
            },
        ),
    ]
