# Generated by Django 6.1 on 2026-08-17 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الوزن (كجم)')),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='نسبة الدهون (%)')),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الكتلة العضلية (كجم)')),
                ('water_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='نسبة الماء (%)')),
                ('bone_mass_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='الكتلة العظمية (كجم)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('source', models.CharField(choices=[('manual', 'يدوي'), ('withings', 'Withings'), ('xiaomi', 'Xiaomi'), ('apple_health', 'Apple Health'), ('google_fit', 'Google Fit'), ('garmin', 'Garmin'), ('import', 'استيراد')], default='manual', max_length=20, verbose_name='المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_measurements', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'قياس جسم',
                'verbose_name_plural': 'قياسات الجسم',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('device_type', models.CharField(choices=[('scale', 'ميزان'), ('watch', 'ساعة'), ('band', 'سوار'), ('strap', 'حزام')], max_length=10, verbose_name='النوع')),
                ('brand', models.CharField(max_length=50, verbose_name='العلامة التجارية')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='الموديل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('oauth_data', models.JSONField(blank=True, null=True, verbose_name='بيانات OAuth')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جهاز',
                'verbose_name_plural': 'أجهزة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(choices=[('weight', 'الوزن'), ('body_fat', 'نسبة الدهون'), ('muscle_mass', 'الكتلة العضلية'), ('heart_rate', 'النبض'), ('steps', 'الخطوات'), ('sleep', 'النوم'), ('calories', 'السعرات')], max_length=20, verbose_name='نوع القياس')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='القيمة')),
                ('unit', models.CharField(max_length=10, verbose_name='الوحدة')),
                ('measured_at', models.DateTimeField(verbose_name='وقت القياس')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='البيانات الأولية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='body_measurements.device', verbose_name='الجهاز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_measurements', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'قياس جهاز',
                'verbose_name_plural': 'قياسات الأجهزة',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('image', models.ImageField(upload_to='progress/', verbose_name='الصورة')),
                ('photo_type', models.CharField(choices=[('front', 'أمامي'), ('back', 'خلفي'), ('side', 'جانبي'), ('other', 'أخرى')], default='front', max_length=10, verbose_name='نوع الصورة')),
                ('weight_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الوزن وقتها (كجم)')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'صورة تقدم',
                'verbose_name_plural': 'صور التقدم',
                'ordering': ['-date'],
            },
        ),
    ]
