# Generated by Django 6.1 on 2026-08-17 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'فئة طعام',
                'verbose_name_plural': 'فئات الطعام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالعربي')),
                ('calories_per_100g', models.PositiveIntegerField(verbose_name='السعرات/100غ')),
                ('protein_per_100g', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='البروتين/100غ')),
                ('carbs_per_100g', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='الكربوهيدرات/100غ')),
                ('fat_per_100g', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='الدهون/100غ')),
                ('fiber_per_100g', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='الألياف/100غ')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='الباركود')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/', verbose_name='الصورة')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nutrition_plan.foodcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'عنصر غذائي',
                'verbose_name_plural': 'عناصر غذائية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyNutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('meal_name', models.CharField(max_length=100, verbose_name='اسم الوجبة')),
                ('amount_g', models.PositiveIntegerField(verbose_name='الكمية (غ)')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='السعرات')),
                ('protein', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='البروتين')),
                ('carbs', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='الكربوهيدرات')),
                ('fat', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='الدهون')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition_plan.fooditem', verbose_name='الطعام')),
            ],
            options={
                'verbose_name': 'سجل تغذية يومي',
                'verbose_name_plural': 'سجلات التغذية اليومية',
                'ordering': ['-date', 'meal_name'],
            },
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخطة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('daily_calories', models.PositiveIntegerField(verbose_name='السعرات اليومية')),
                ('protein_g', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='البروتين (غ)')),
                ('carbs_g', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='الكربوهيدرات (غ)')),
                ('fat_g', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='الدهون (غ)')),
                ('is_template', models.BooleanField(default=False, verbose_name='قالب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plans', to=settings.AUTH_USER_MODEL, verbose_name='المدرب')),
            ],
            options={
                'verbose_name': 'خطة تغذية',
                'verbose_name_plural': 'خطط التغذية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_nutrition_plans', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_nutrition_plans', to=settings.AUTH_USER_MODEL, verbose_name='المدرب')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition_plan.nutritionplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'خطة تغذية للعميل',
                'verbose_name_plural': 'خطط تغذية العملاء',
                'ordering': ['-created_at'],
            },
        ),
    ]
