# Generated by Django 5.0.9 on 2026-08-27 01:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acct', '0001_initial'),
        ('gym_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('calories_per_100g', models.PositiveIntegerField(default=0, verbose_name='Calories / 100g')),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Protein (g)')),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Carbs (g)')),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Fat (g)')),
                ('fiber_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Fiber (g)')),
                ('category', models.CharField(choices=[('protein', 'Protein'), ('carbs', 'Carbohydrates'), ('fats', 'Fats'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('supplements', 'Supplements'), ('other', 'Other')], default='other', max_length=20, verbose_name='Category')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Custom Food')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('name', models.CharField(help_text='e.g. "Breakfast"', max_length=100, verbose_name='Meal Name')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Calories')),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Protein (g)')),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Carbs (g)')),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Fat (g)')),
                ('instructions', models.TextField(blank=True, verbose_name='Preparation Instructions')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('quantity_g', models.DecimalField(decimal_places=1, default=100, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity (g)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to='nutrition_plan.food', verbose_name='Food')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='nutrition_plan.meal', verbose_name='Meal')),
            ],
            options={
                'verbose_name': 'Meal Food',
                'verbose_name_plural': 'Meal Foods',
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Plan Name')),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('clean_bulk', 'Clean Bulk')], default='maintenance', max_length=20, verbose_name='Goal')),
                ('daily_calories', models.PositiveIntegerField(default=2000, verbose_name='Daily Calories')),
                ('protein_target_g', models.PositiveIntegerField(default=150, verbose_name='Protein Target (g)')),
                ('carbs_target_g', models.PositiveIntegerField(default=200, verbose_name='Carbs Target (g)')),
                ('fat_target_g', models.PositiveIntegerField(default=60, verbose_name='Fat Target (g)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_template', models.BooleanField(default=True, verbose_name='Is Template')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_meal_plans', to='acct.clientprofile', verbose_name='Assigned Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_plans', to='acct.trainerprofile', verbose_name='Trainer')),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition_plan.mealplan', verbose_name='Plan'),
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('quantity_g', models.DecimalField(decimal_places=1, default=100, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity (g)')),
                ('calories', models.PositiveIntegerField(default=0, verbose_name='Calories')),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Protein (g)')),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Carbs (g)')),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Fat (g)')),
                ('water_ml', models.PositiveIntegerField(default=0, verbose_name='Water (ml)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to='acct.clientprofile', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nutrition_plan.food', verbose_name='Food')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='nutrition_plan.mealplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Nutrition Log',
                'verbose_name_plural': 'Nutrition Logs',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['gym', 'category'], name='nutrition_p_gym_id_83ef07_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionlog',
            index=models.Index(fields=['client', '-date'], name='nutrition_p_client__d6963e_idx'),
        ),
    ]
