# Generated by Django 6.1 on 2026-08-17 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المركز')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym_logos/', verbose_name='الشعار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_gyms', to=settings.AUTH_USER_MODEL, verbose_name='المالك')),
            ],
            options={
                'verbose_name': 'مركز رياضي',
                'verbose_name_plural': 'مراكز رياضية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='وقت الدخول')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('qr_code', models.CharField(blank=True, max_length=100, verbose_name='رمز QR')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_center.gymcenter', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'حضور',
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('membership_type', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', '3 أشهر'), ('yearly', 'سنوي'), ('lifetime', ' مدى الحياة')], default='monthly', max_length=15, verbose_name='نوع العضوية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('activated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_memberships', to=settings.AUTH_USER_MODEL, verbose_name='فعّلها')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_memberships', to=settings.AUTH_USER_MODEL, verbose_name='المدرب')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_center.gymcenter', verbose_name='المركز')),
            ],
            options={
                'verbose_name': 'عضوية',
                'verbose_name_plural': 'عضويات',
                'ordering': ['-created_at'],
            },
        ),
    ]
