# Generated by Django 5.0.9 on 2026-08-27 01:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(default=uuid.uuid4, help_text='Tenant sharding id', unique=True)),
                ('slug', models.SlugField(help_text='Used for subdomain: slug.fitpro.hftv.qzz.io', unique=True, verbose_name='Slug / Subdomain')),
                ('name', models.CharField(max_length=120, verbose_name='Gym Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('custom_domain', models.CharField(blank=True, help_text='Optional full domain', max_length=255, verbose_name='Custom Domain')),
                ('kind', models.CharField(choices=[('gym', 'Gym'), ('personal', 'Personal Trainer App')], default='gym', max_length=10, verbose_name='Account Kind')),
                ('primary_color', models.CharField(default='#38BDF8', max_length=7, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#22D3EE', max_length=7, verbose_name='Secondary Color')),
                ('accent_color', models.CharField(default='#4ADE80', max_length=7, verbose_name='Accent Color')),
                ('background_color', models.CharField(default='#0F172A', max_length=7, verbose_name='Background Color')),
                ('surface_color', models.CharField(default='#1E293B', max_length=7, verbose_name='Surface Color')),
                ('default_theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=5, verbose_name='Default Theme')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='gyms/banners/', verbose_name='Banner')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='gyms/backgrounds/', verbose_name='Background Image')),
                ('splash_title', models.CharField(blank=True, max_length=120, verbose_name='Splash Title')),
                ('splash_tagline', models.CharField(blank=True, max_length=200, verbose_name='Splash Tagline')),
                ('splash_style', models.CharField(choices=[('gradient', 'Brand Gradient'), ('solid', 'Solid Brand'), ('minimal', 'Minimal Dark')], default='gradient', max_length=12, verbose_name='Splash Style')),
                ('splash_image', models.ImageField(blank=True, null=True, upload_to='gyms/splash/', verbose_name='Splash Background')),
                ('font_family', models.CharField(default='Cairo', max_length=50, verbose_name='Font Family')),
                ('font_weight_regular', models.PositiveSmallIntegerField(default=400)),
                ('font_weight_medium', models.PositiveSmallIntegerField(default=600)),
                ('font_weight_bold', models.PositiveSmallIntegerField(default=700)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gyms/logos/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='gyms/favicons/', verbose_name='Favicon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Contact Phone')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('website_url', models.URLField(blank=True, verbose_name='Website')),
                ('meta_title', models.CharField(blank=True, max_length=120, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gym',
                'verbose_name_plural': 'Gyms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Gym Name')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym_logos/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_gyms', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Gym Center',
                'verbose_name_plural': 'Gym Centers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='Check In')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Check Out')),
                ('qr_code', models.CharField(blank=True, max_length=100, verbose_name='QR Code')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_center.gymcenter', verbose_name='Gym')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='GymInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('trainer', 'Trainer'), ('client', 'Client'), ('gym_admin', 'Gym Admin')], default='client', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='gym_center.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('membership_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime')], default='monthly', max_length=15, verbose_name='Membership Type')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Activated By')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Coach')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_center.gymcenter', verbose_name='Gym')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'ordering': ['-created_at'],
            },
        ),
    ]
