# Generated by Django 5.0.9 on 2026-08-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='gym',
            name='currency',
            field=models.CharField(default='EGP', max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='gym',
            name='notification_config',
            field=models.JSONField(blank=True, default=dict, help_text='{"channels": {"email": true, "sms": false, "push": true}, "events": {...}, "expiry_reminder_days": 3}', verbose_name='Notification Config'),
        ),
        migrations.AddField(
            model_name='gym',
            name='opening_hours',
            field=models.JSONField(blank=True, default=dict, help_text='{"sat": "9:00-23:00", "fri": "closed"}', verbose_name='Opening Hours'),
        ),
    ]
