# Generated by Django 5.0.9 on 2026-08-27 01:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, help_text='Used in URL: /coach/{slug}/', unique=True, verbose_name='Slug')),
                ('display_name', models.CharField(max_length=100, verbose_name='Display Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='coach_logos/', verbose_name='Logo')),
                ('tagline', models.CharField(blank=True, help_text='Short phrase under the name', max_length=255, verbose_name='Tagline')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('primary_color', models.CharField(default='#22c55e', help_text='hex color like #22c55e', max_length=7, verbose_name='Primary Color')),
                ('secondary_color', models.CharField(default='#16a34a', max_length=7, verbose_name='Secondary Color')),
                ('background_color', models.CharField(default='#f0fdf4', max_length=7, verbose_name='Background Color')),
                ('text_color', models.CharField(default='#14532d', max_length=7, verbose_name='Text Color')),
                ('font_family', models.CharField(default='Tajawal', help_text='Google Fonts name', max_length=100, verbose_name='Font Family')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('social_instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('social_twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('social_tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('social_youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Coach Profile',
                'verbose_name_plural': 'Coach Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymAdminProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Custom permissions override: {"manage_trainers": true, "view_analytics": true}', verbose_name='Custom Permissions')),
            ],
            options={
                'verbose_name': 'Gym Admin Profile',
                'verbose_name_plural': 'Gym Admin Profiles',
            },
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('employee_id', models.CharField(help_text='Unique employee code', max_length=50, unique=True, verbose_name='Employee ID')),
                ('specialization', models.JSONField(blank=True, default=list, help_text='List of specializations: ["Strength", "Cardio", "Rehab"]', verbose_name='Specializations')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='List of certifications', verbose_name='Certifications')),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('max_clients', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Max Clients')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate for payroll', max_digits=10, verbose_name='Hourly Rate')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Trainer Profile',
                'verbose_name_plural': 'Trainer Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Occupation')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Company')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Skills')),
                ('certifications', models.JSONField(blank=True, default=list, verbose_name='Certifications')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, verbose_name='Relation')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='Blood Type')),
                ('allergies', models.TextField(blank=True, verbose_name='Allergies')),
                ('medications', models.TextField(blank=True, verbose_name='Medications')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Medical Conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, verbose_name='Gender')),
                ('avatar', models.ImageField(blank=True, help_text='Profile picture, max 2MB', null=True, upload_to='users/avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('gym_admin', 'Gym Admin'), ('trainer', 'Trainer'), ('client', 'Client')], default='client', max_length=20, verbose_name='Role')),
                ('profile_completion', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Profile Completion %')),
                ('is_profile_complete', models.BooleanField(default=False, verbose_name='Profile Complete')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=10, verbose_name='Language')),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50, verbose_name='Timezone')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications Enabled')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email Notifications')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push Notifications')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS Notifications')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Login At')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Locked Until')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('email_verification_token', models.UUIDField(blank=True, null=True)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('phone_verified', models.BooleanField(default=False, verbose_name='Phone Verified')),
                ('phone_verification_code', models.CharField(blank=True, max_length=6, verbose_name='Phone Verification Code')),
                ('phone_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('membership_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP'), ('trial', 'Trial')], default='basic', max_length=20, verbose_name='Membership Type')),
                ('membership_start', models.DateField(verbose_name='Membership Start')),
                ('membership_end', models.DateField(verbose_name='Membership End')),
                ('goals', models.JSONField(blank=True, default=list, help_text='Fitness goals: ["Weight Loss", "Muscle Gain"]', verbose_name='Goals')),
                ('medical_notes', models.TextField(blank=True, verbose_name='Medical Notes')),
                ('emergency_contact', models.JSONField(blank=True, default=dict, help_text='{"name": "", "phone": "", "relation": ""}', verbose_name='Emergency Contact')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
