# Generated by Django 6.1 on 2026-08-17 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, help_text='يُستخدم في الرابط: /coach/{slug}/', unique=True, verbose_name='الرابط الفريد')),
                ('display_name', models.CharField(max_length=100, verbose_name='اسم العرض')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='coach_logos/', verbose_name='اللوجو')),
                ('tagline', models.CharField(blank=True, help_text='جملة قصيرة تحت الاسم', max_length=255, verbose_name='الشعار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('primary_color', models.CharField(default='#22c55e', help_text='hex color like #22c55e', max_length=7, verbose_name='اللون الرئيسي')),
                ('secondary_color', models.CharField(default='#16a34a', max_length=7, verbose_name='اللون الثانوي')),
                ('background_color', models.CharField(default='#f0fdf4', max_length=7, verbose_name='لون الخلفية')),
                ('text_color', models.CharField(default='#14532d', max_length=7, verbose_name='لون النص')),
                ('font_family', models.CharField(default='Tajawal', help_text='اسم الخط من Google Fonts', max_length=100, verbose_name='الخط')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='هاتف التواصل')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد التواصل')),
                ('social_instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('social_twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('social_tiktok', models.URLField(blank=True, verbose_name='TikTok')),
                ('social_youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التعديل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coach_profile', to=settings.AUTH_USER_MODEL, verbose_name='المدرب')),
            ],
            options={
                'verbose_name': 'بروفايل المدرب',
                'verbose_name_plural': 'بروفايلات المدربين',
            },
        ),
    ]
