# Generated by Django 5.0.9 on 2026-08-27 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acct', '0003_reconcile_roles'),
        ('gym_center', '0002_gym_address_gym_currency_gym_notification_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='membership_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subscription amount in EGP, entered manually by the gym admin', max_digits=10, verbose_name='Membership Fee (EGP)'),
        ),
        migrations.AddField(
            model_name='gymadminprofile',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary Admin'),
        ),
        migrations.AlterField(
            model_name='gymadminprofile',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profiles', to='gym_center.gym', verbose_name='Gym'),
        ),
        migrations.AlterField(
            model_name='gymadminprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Permission overrides: {"manage_members": false, "manage_trainers": false} — unset keys stay allowed', verbose_name='Custom Permissions'),
        ),
    ]
