# Generated by Django 5.0.9 on 2026-08-27 01:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acct', '0001_initial'),
        ('gym_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('full_body', 'Full Body'), ('cardio', 'Cardio')], max_length=20, verbose_name='Muscle Group')),
                ('equipment', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('bodyweight', 'Bodyweight'), ('kettlebell', 'Kettlebell'), ('other', 'Other')], default='bodyweight', max_length=20, verbose_name='Equipment')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='Difficulty')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('gif_url', models.URLField(blank=True, verbose_name='GIF URL')),
                ('instructions', models.JSONField(blank=True, default=list, verbose_name='Instructions')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Custom Exercise')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('day_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Day Number')),
                ('name', models.CharField(help_text='e.g. "Upper Body"', max_length=100, verbose_name='Day Name')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
            ],
            options={
                'verbose_name': 'Workout Day',
                'verbose_name_plural': 'Workout Days',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('sets', models.PositiveIntegerField(default=3, verbose_name='Sets')),
                ('reps', models.CharField(default='10', help_text='e.g. "8-12" or "AMRAP"', max_length=20, verbose_name='Reps')),
                ('rest_seconds', models.PositiveIntegerField(default=90, verbose_name='Rest (seconds)')),
                ('tempo', models.CharField(blank=True, help_text='e.g. "3-0-1-0"', max_length=20, verbose_name='Tempo')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_tracking.workoutday', verbose_name='Day')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='workout_tracking.exercise', verbose_name='Exercise')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
            ],
            options={
                'verbose_name': 'Workout Exercise',
                'verbose_name_plural': 'Workout Exercises',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Plan Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration_weeks', models.PositiveIntegerField(default=4, verbose_name='Duration (weeks)')),
                ('days_per_week', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Days Per Week')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='Level')),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('general', 'General Fitness')], default='general', max_length=20, verbose_name='Goal')),
                ('is_template', models.BooleanField(default=True, verbose_name='Is Template')),
                ('client', models.ForeignKey(blank=True, help_text='Set when the plan is assigned to a specific client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workout_plans', to='acct.clientprofile', verbose_name='Assigned Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plans', to='acct.trainerprofile', verbose_name='Trainer')),
            ],
            options={
                'verbose_name': 'Workout Plan',
                'verbose_name_plural': 'Workout Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (minutes)')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='in_progress', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Client Notes')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1-5)')),
                ('trainer_feedback', models.TextField(blank=True, verbose_name='Trainer Feedback')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to='acct.clientprofile', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='workout_tracking.workoutday', verbose_name='Day')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='workout_tracking.workoutplan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Workout Log',
                'verbose_name_plural': 'Workout Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='workoutday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='workout_tracking.workoutplan', verbose_name='Plan'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['gym', 'muscle_group'], name='workout_tra_gym_id_842b21_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutlog',
            index=models.Index(fields=['client', '-started_at'], name='workout_tra_client__99c19b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('plan', 'day_number')},
        ),
    ]
