# Generated by Django 6.1 on 2026-08-17 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise_db', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_plans', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_plans', to=settings.AUTH_USER_MODEL, verbose_name='المدرب')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_db.workoutplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'خطة العميل',
                'verbose_name_plural': 'خطط العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='وقت البداية')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='التقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('day', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercise_db.workoutday', verbose_name='اليوم')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_tracking.clientplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'جلسة تدريب',
                'verbose_name_plural': 'جلسات التدريب',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_completed', models.PositiveIntegerField(verbose_name='المجموعات المنجزة')),
                ('reps_completed', models.CharField(max_length=50, verbose_name='التكرارات المنجزة')),
                ('weight_used', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الوزن المستخدم (كجم)')),
                ('rest_taken', models.PositiveIntegerField(blank=True, null=True, verbose_name='الراحة المأخوذة (ثانية)')),
                ('rir', models.PositiveIntegerField(blank=True, null=True, verbose_name='RIR')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_db.exercise', verbose_name='التمرين')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workout_tracking.workoutsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'سجل تمرين',
                'verbose_name_plural': 'سجلات التمارين',
                'ordering': ['created_at'],
            },
        ),
    ]
