# Generated by Django 5.0.9 on 2026-08-27 01:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acct', '0001_initial'),
        ('gym_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Goal Title')),
                ('goal_type', models.CharField(choices=[('weight', 'Weight'), ('body_fat', 'Body Fat %'), ('muscle_mass', 'Muscle Mass'), ('waist', 'Waist Circumference'), ('performance', 'Performance'), ('custom', 'Custom')], default='weight', max_length=20, verbose_name='Goal Type')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Target Value')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Current Value')),
                ('unit', models.CharField(default='kg', max_length=20, verbose_name='Unit')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('target_date', models.DateField(verbose_name='Target Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('achieved', 'Achieved'), ('behind', 'Behind'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status')),
                ('trainer_notes', models.TextField(blank=True, verbose_name='Trainer Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_goals', to='acct.clientprofile', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('photo', models.ImageField(upload_to='progress/%Y/%m/', verbose_name='Photo')),
                ('photo_type', models.CharField(choices=[('front', 'Front'), ('side', 'Side'), ('back', 'Back'), ('custom', 'Custom')], default='front', max_length=20, verbose_name='Photo Type')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Weight at Photo (kg)')),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Body Fat (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_private', models.BooleanField(default=False, verbose_name='Private (trainer only)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to='acct.clientprofile', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
            ],
            options={
                'verbose_name': 'Progress Photo',
                'verbose_name_plural': 'Progress Photos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='progress_pr_client__edbff7_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyCheckin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('week_start', models.DateField(verbose_name='Week Start')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weight (kg)')),
                ('body_fat_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Body Fat (%)')),
                ('measurements', models.JSONField(blank=True, default=dict, help_text='{"chest": 100, "waist": 85, "hips": 95, "arm": 35, "thigh": 58}', verbose_name='Measurements')),
                ('energy_level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Energy Level (1-5)')),
                ('sleep_quality', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Sleep Quality (1-5)')),
                ('stress_level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Stress Level (1-5)')),
                ('adherence', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Plan Adherence (1-5)')),
                ('client_notes', models.TextField(blank=True, verbose_name='Client Notes')),
                ('trainer_feedback', models.TextField(blank=True, verbose_name='Trainer Feedback')),
                ('next_week_adjustments', models.TextField(blank=True, verbose_name='Next Week Adjustments')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='acct.clientprofile', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
            ],
            options={
                'verbose_name': 'Weekly Check-in',
                'verbose_name_plural': 'Weekly Check-ins',
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['client', '-week_start'], name='progress_we_client__e21e78_idx')],
                'unique_together': {('client', 'week_start')},
            },
        ),
    ]
