# Generated by Django 5.0.9 on 2026-08-27 01:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acct', '0002_initial'),
        ('gym_center', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('name', models.CharField(max_length=120, verbose_name='Device Name')),
                ('device_type', models.CharField(choices=[('watch', 'Smart Watch'), ('scale', 'Smart Scale'), ('band', 'Fitness Band'), ('machine', 'Gym Machine'), ('other', 'Other')], default='watch', max_length=20, verbose_name='Type')),
                ('identifier', models.CharField(blank=True, max_length=100, verbose_name='Identifier / MAC')),
                ('status', models.CharField(choices=[('paired', 'Paired'), ('pending', 'Pending'), ('disconnected', 'Disconnected')], default='pending', max_length=20, verbose_name='Status')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='acct.clientprofile', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(blank=True, help_text='Tenant copy of gym id for sharding', null=True)),
                ('kind', models.CharField(help_text='steps, heart_rate, weight, etc.', max_length=30, verbose_name='Kind')),
                ('value', models.FloatField(verbose_name='Value')),
                ('recorded_at', models.DateTimeField(verbose_name='Recorded At')),
                ('raw', models.JSONField(blank=True, default=dict, verbose_name='Raw Payload')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='devices.device')),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='gym_center.gym')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='devices_dev_device__8c821b_idx')],
            },
        ),
    ]
