# Generated by Django 6.1 on 2026-08-17 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالعربي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'معدات',
                'verbose_name_plural': 'معدات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالعربي')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='الأيقونة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'فئة التمرين',
                'verbose_name_plural': 'فئات التمارين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='الاسم')),
                ('is_front', models.BooleanField(default=True, verbose_name='من الأمام')),
                ('image', models.ImageField(blank=True, null=True, upload_to='muscles/', verbose_name='الصورة')),
            ],
            options={
                'verbose_name': 'مجموعة عضلية',
                'verbose_name_plural': 'مجموعات عضلية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم اليوم')),
                ('day_number', models.PositiveIntegerField(verbose_name='رقم اليوم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'يوم تدريب',
                'verbose_name_plural': 'أيام التدريب',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='الاسم بالعربي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربي')),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='intermediate', max_length=15, verbose_name='المستوى')),
                ('instructions', models.TextField(blank=True, verbose_name='التعليمات')),
                ('video_url', models.URLField(blank=True, verbose_name='رابط الفيديو')),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='الصورة')),
                ('equipment', models.ManyToManyField(blank=True, to='exercise_db.equipment', verbose_name='المعدات')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_db.exercisecategory', verbose_name='الفئة')),
                ('primary_muscles', models.ManyToManyField(related_name='primary_exercises', to='exercise_db.musclegroup', verbose_name='العضلات الرئيسية')),
                ('secondary_muscles', models.ManyToManyField(blank=True, related_name='secondary_exercises', to='exercise_db.musclegroup', verbose_name='العضلات الثانوية')),
            ],
            options={
                'verbose_name': 'تمرين',
                'verbose_name_plural': 'تمارين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=3, verbose_name='المجموعات')),
                ('reps', models.CharField(default='8-12', max_length=50, verbose_name='التكرارات')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الوزن (كجم)')),
                ('rest_seconds', models.PositiveIntegerField(default=60, verbose_name='وقت الراحة (ثانية)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('exercise_type', models.CharField(choices=[('normal', 'عادي'), ('warmup', 'إحماء'), ('dropset', 'Drop Set'), ('superset', 'Superset')], default='normal', max_length=10, verbose_name='نوع التمرين')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise_db.workoutday', verbose_name='اليوم')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercise_db.exercise', verbose_name='التمرين')),
            ],
            options={
                'verbose_name': 'تمرين في اليوم',
                'verbose_name_plural': 'تمارين الأيام',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الخطة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='intermediate', max_length=15, verbose_name='المستوى')),
                ('duration_weeks', models.PositiveIntegerField(default=4, verbose_name='المدة (أسابيع)')),
                ('is_template', models.BooleanField(default=False, verbose_name='قالب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='المدرب')),
            ],
            options={
                'verbose_name': 'خطة تدريب',
                'verbose_name_plural': 'خطط التدريب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='workoutday',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='exercise_db.workoutplan', verbose_name='الخطة'),
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('plan', 'day_number')},
        ),
    ]
