# Generated by Django 5.0.9 on 2026-08-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseCatalog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='Name (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('full_body', 'Full Body'), ('cardio', 'Cardio')], max_length=20, verbose_name='Muscle Group')),
                ('equipment', models.CharField(default='bodyweight', max_length=20, verbose_name='Equipment')),
                ('difficulty', models.CharField(default='beginner', max_length=20, verbose_name='Difficulty')),
                ('video_url', models.URLField(blank=True)),
                ('gif_url', models.URLField(blank=True)),
                ('instructions', models.JSONField(blank=True, default=list)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exercise Catalog',
                'verbose_name_plural': 'Exercise Catalog',
                'ordering': ['name'],
            },
        ),
    ]
